name: Fly Deploy

on:
  push:
    branches:
      - main   # change if your default branch is different
    # Optional: only deploy when these paths change
    # paths:
    #   - "app/**"
    #   - "scripts/**"
    #   - "fly.toml"
    #   - "Dockerfile"
    #   - "requirements.txt"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
